# Generated by Django 5.2.4 on 2025-07-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_your_wealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='company',
            field=models.CharField(default='Mansa-X', max_length=50),
        ),
        migrations.AddField(
            model_name='investment',
            name='duration_in_years',
            field=models.IntegerField(default=10, help_text='integer'),
        ),
        migrations.AddField(
            model_name='investment',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.15, help_text='decimal point between 0 and 1 with only 2 decimal places allowed', max_digits=5),
        ),
        migrations.AddField(
            model_name='investment',
            name='top_up',
            field=models.DecimalField(decimal_places=2, default=250000, max_digits=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='topup_frequency',
            field=models.CharField(default='month', max_length=20),
        ),
    ]
