# Generated by Django 5.2.4 on 2025-07-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_your_wealth', '0002_investment_company_investment_duration_in_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='company',
            field=models.CharField(default='Mansa-X', help_text='name of company. Optional field', max_length=50),
        ),
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.CharField(help_text='investment name e.g. retirement', max_length=100),
        ),
    ]
